[project]
name = "weatherquery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fexcode", email = "14356165+fexcode@user.noreply.gitee.com" }
]
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
